mysite/GIRng/urls.py
from django.urls import path, include

from . import views

app_name = 'GIRng'

urlpatterns = [
    path('', views.index, name='index'),
    # teams api
    path('teams/random/', views.create_random_team, name='randomize'),
    # team management
    path('teams/add/', views.add_team, name='add-team'),
    path('teams', views.team_list, name='team-list'),
    path('teams/<int:team_id>/', views.team_detail, name='team-detail'),
    # path('teams/update/<int:team_id>/', TODO)
    # path('teams/delete/<int:team_id>/, TODO)
    
    # characters management
    path('characters/',
         views.CharacterListView.as_view(),
         name='characters-list'),
    path('characters/<int:pk>/',
         views.CharacterDetailView.as_view(),
         name='character-detail'),
    # path('characters/add/', TODO: add char feature , TODO),
    # path('characters/update/<int:pk>/', TODO: )
    # path('characters/delete/<int:pk>/', TODO)
    
    # artifacts api
    # TODO: artifact management
    
    # weapons api
    # TODO: weapon management
    
    # auth
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/GIRng/models.py
from django.db import models


class Base(models.Model):

    name = models.CharField(max_length=32, unique=True, blank=False)
    description = models.CharField(max_length=255, blank=True)

    class Meta:
        abstract = True


class Character(Base):
    ELEMENT_CHOICES = [
        ('Pyro', 'Pyro'),
        ('Cryo', 'Cryo'),
        ('Hydro', 'Hydro'),
        ('Geo', 'Geo'),
        ('Anemo', 'Anemo'),
        ('Electro', 'Electro'),
        ('Dendro', 'Dendro')
    ]

    element = models.CharField(max_length=7, choices=ELEMENT_CHOICES)
    level = models.IntegerField(default=90)

    def __str__(self):
        return self.name


class NormalAttack(Base):
    character = models.OneToOneField(Character,
                                     on_delete=models.CASCADE,
                                     primary_key=True,)

    def __str__(self) -> str:
        return self.name


class ElementalSkill(Base):
    cd = models.IntegerField(blank=False)

    character = models.OneToOneField(Character,
                                     on_delete=models.CASCADE,
                                     primary_key=True,)

    def __str__(self) -> str:
        return self.name


class ElementalBurst(Base):
    cd = models.IntegerField(blank=False)

    character = models.OneToOneField(Character,
                                     on_delete=models.CASCADE,
                                     primary_key=True,)

    def __str__(self) -> str:
        return self.name


class Passive(Base):
    character = models.OneToOneField(Character,
                                     on_delete=models.CASCADE,
                                     primary_key=True,)

    def __str__(self) -> str:
        return self.name


class Artifact(Base):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name


class Weapon(Base):
    character = models.OneToOneField(Character,
                                     on_delete=models.CASCADE,
                                     primary_key=True,)

    def __str__(self) -> str:
        return self.name


class Constellation(Base):
    level = models.IntegerField(blank=False)

    character = models.ForeignKey(Character, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

# luu chi so nhu atk, def, em, ...
# class BaseStat(models.Model):


#     character = models.OneToOneField(Character,
#         on_delete=models.CASCADE,
#         primary_key=True,)

class Team(Base):
    name = models.CharField(max_length=32, unique=True)
    members = models.ManyToManyField(Character, through='TeamInfo')
    resonance = models.CharField(default='N/A', max_length=32)

    def __str__(self):
        return self.name


class TeamInfo(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

mysite/GIRng/forms.py
from django import forms

from .models import Character

class TeamForm(forms.Form):
    name = forms.CharField(label="Team Name", max_length=20)
    char_list = forms.ModelMultipleChoiceField(Character.objects.all(),widget=forms.CheckboxSelectMultiple)

mysite/GIRng/views.py
import random
import logging

from django.shortcuts import render, redirect, get_object_or_404

from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader, Template, Context
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Team, Character, TeamInfo
from .forms import TeamForm
# Create your views here.

logger = logging.getLogger("django")

# TODO: make new login interface later


@login_required(login_url='accounts/login/')
def index(request):
    logger.info("Logging: This is index")
    return render(request, 'GIRng/index.html')

# display a form for user to add team


def add_team(request):
    if request.method == 'POST':
        form = TeamForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            char_list = form.cleaned_data['char_list']

            # get resonance from list of character
            # resonance = resonance(char_list)

            team = Team(name=name)
            team.save()
            for char in char_list:
                tmp = TeamInfo(character=char, team=team)
                tmp.save()

            return redirect('GIRng:team-list')
    else:
        form = TeamForm()
        return render(request, 'GIRng/team.html', {'form': form})


@staticmethod
def randomize():
    all_char = list(Character.objects.all())

    # use random.sample to create new Team
    # how to bind char to member?
    # cai nay nen tra lai mot list chua cac Character
    char_list = random.sample(all_char, 4)

    return char_list


def create_random_team(request):
    # why do i need object team? to store team ? to add team attribute later
    # team generated from char list, 4 char added to member field
    # -> generate when init team ?
    # change __init__ then in generate(request) create a new team like so:
    # on second though, just create a generate function to generate the chars
    # in team

    try:
        char_list = randomize()
    #    raise ValueError("Character not found")
    except ValueError as err:
        raise Http404(f"{str(err)}")

    # how do i pass team info to template ?
    # -> what info do i want to put on template?
    # for now i want to pass 'name' to template,
    # but there can be more in the future
    # -> add info to context like so:

    context = {
        'members': char_list,
        'number': len(char_list),
    }

    # after context is added, render either through shortcut or through loader
    # i do not  use generic views for now

    template = loader.get_template('GIRng/randomize.html')

    return HttpResponse(template.render(context, request))

    # short cut
    # return render(request, 'GIRng/team.html', context)


def team_list(request):
    # team list
    try:
        t = Team.objects.all()
    except Exception as err:
        raise Http404(f"{str(err)}")

    return render(request, 'GIRng/team_list.html', {'teamlist': t, })


def team_detail(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    context = {
        "team_name": team.name,
    }
    return render(request, 'GIRng/team_detail.html', context)


class CharacterListView(ListView):
    model = Character
    context_object_name = 'character_list'


class CharacterDetailView(DetailView, LoginRequiredMixin):
    model = Character


class SignupView(View):
    pass

mysite/GIRng/templates/GIRng/character_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        <h1> {{object.name}} </h1>
        <h1> {{object.element }} </h1>
    </ul>
</body>
</html>

mysite/GIRng/templates/GIRng/character_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Characters list</title>
</head>
<body>
    {% block content %}
    <h2>Characters</h2>
    <ul>
        {% for character in character_list %}
            <li><a href="{% url 'GIRng:character-detail' character.id %}">{{ character.name }}</a></li>
        {% endfor %}
    </ul>
    {% endblock %}
</body>
</html>

mysite/GIRng/templates/GIRng/header.html
<div>
    
</div>

mysite/GIRng/templates/GIRng/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}
    <link rel="stylesheet" href=" {% static 'GIRng/css/mycss.css' %} ">

    <title>Index</title>
</head>
<body>
    
    <div class="container">
        <div class="center">
            <button class="block">
                <a href="{% url 'GIRng:randomize' %}">Generate Random Team</a>
            </button>
        </div>
        <div>
            <button class="block">
                <a href="{% url 'GIRng:add-team' %}">Add Team</a>
            </button>
        </div>
        <div>
            <button class="block">
                <a href="">Elastic Search</a>
            </button>
        </div>
        <div>
            <button class="block">
                <a href=" {% url 'GIRng:characters-list' %} ">Characters</a>
            </button>
        </div>
        <div>
            <button class="block">
                <a href=" {% url 'GIRng:team-list' %} ">Teams</a>
            </button>
        </div>
        <div>
            <button class="block">
                <a href="#">Login</a>
            </button>
        </div>
    </div>
    
    
</body>
</html>

mysite/GIRng/templates/GIRng/randomize.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href=" {% static 'GIRng/css/mycss.css' %} ">

    <title>Team</title>
</head>
<body>
    {% include "GIRng/header.html" %}
    <ul>
        {% for mem in members %}
        <li> {{ mem.name }}</li>
        {% endfor %}
    </ul>
</body>
</html>

mysite/GIRng/templates/GIRng/team.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% load static %}
    <link rel="stylesheet" href=" {% static 'GIRng/css/mycss.css' %} ">
    
    {% load bootstrap5 %}
</head>
<body>
    {% comment %} tao mot form de them team {% endcomment %}
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <label for="">Team name: </label>
            {{ form.name }}
            <br>
            <label for="">Character list: </label>
            {{ form.char_list}}
            <br>
            <input type="submit" value="Submit">
        </form>
    </div>
    
    {% include 'bootstrap5/field_help_text.html' %}
</body>
</html>

mysite/GIRng/templates/GIRng/team_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        <h1> {{team_name}} </h1>
        
    </ul>
</body>
</html>

mysite/GIRng/templates/GIRng/team_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href=" {% static 'GIRng/css/mycss.css' %} ">

    <title>Team List</title>
</head>
<body>  
    <p for="">Teams: </p>
    {% for team in teamlist %}
        <a href="{% url 'GIRng:team-detail' team.id %}"> {{ team.name }} </a>
        <br>
    {% endfor %}

    
</body>
</html>